ARG BASE_IMAGE=cyberbotics/webots:latest
FROM $BASE_IMAGE AS downloader

# Determine Webots version to be used and set default argument
ARG WEBOTS_VERSION=R2022b

RUN apt update && apt install --yes unzip && \
  wget https://github.com/cyberbotics/webots/releases/download/$WEBOTS_VERSION/assets-$WEBOTS_VERSION.zip && \
  mkdir assets && cp assets-$WEBOTS_VERSION.zip assets/ && \
  cd assets && unzip assets-$WEBOTS_VERSION.zip && rm assets-$WEBOTS_VERSION.zip

FROM $BASE_IMAGE

COPY Webots-R2022b.conf /root/.config/Cyberbotics/Webots-$WEBOTS_VERSION.conf
COPY --from=downloader /usr/local/assets /root/.cache/Cyberbotics/Webots/assets/
