version: "3.9"
services:
  webots_docker:
    extends:
      file: docker-compose-gui.yml
      service: webots_nvidia
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
