version: "3.9"
services:
  webots_cloud:
    extends:
      file: docker-compose.yml
      service: webots_cloud
    environment:
     - DISPLAY=${DISPLAY:-0}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
  webots_nvidia:
    extends:
      file: docker-compose.yml
      service: webots_nvidia
    environment:
     - DISPLAY=${DISPLAY:-0}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
